#!/bin/bash
# Print available disk space for all the disks present in the diskspace.conf file
# Contributed by: TA Sayan Ghosh

xargs -I {} lsblk -rno FSAVAIL /dev/{} < "$HOME/.config/diskspace.conf" | paste -s -d " "
