#!/bin/bash
#
# Take user's input and search it on google
# Contributed by: TA Sayan Ghosh
#


# if sent as argument, take that as input, else use GUI input box
if [[ $# -gt 0 ]]; then
  input="$*"
else
  input=$(echo | rofi -dmenu -i -scroll-method 1 -p ' search')
fi

if [[ -n "$input" ]]; then
	${BROWSER:-chromium} "google.com/search?q=$input" &
fi
